import {
  User,
  StrategicPillar,
  Employee,
  IndividualKPI,
  SOPComplianceRecord,
  PeerReview360,
  PerformanceAppraisal,
  ManpowerPlan,
  RecruitmentAssessment,
  OnboardingMilestone,
  OffboardingRequest,
  KnowledgeHandover,
  SeveranceCalculation,
  LifetimeContribution,
  AuditLog,
} from '@/types';

// 1. Five Main Role Users
export const DUMMY_USERS: User[] = [
  {
    id: 'usr-bod-001',
    employeeId: 'emp-bod-001',
    email: 'hendra.gunawan@eperformiq.co.id',
    name: 'Ir. Hendra Gunawan, M.B.A.',
    role: 'BOD',
    department: 'Dewan Direksi (Board of Directors)',
    position: 'Chief Executive Officer (CEO)',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-hrm-002',
    employeeId: 'emp-hrm-002',
    email: 'siti.nurhaliza@eperformiq.co.id',
    name: 'Siti Nurhaliza, S.Psi., M.M.',
    role: 'HR_MANAGER',
    department: 'Human Capital & Corporate Governance',
    position: 'VP of Human Capital',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mgr-003',
    employeeId: 'emp-mgr-003',
    email: 'danu.tech@eperformiq.co.id',
    name: 'Raden Mas Danu, S.T., M.Kom.',
    role: 'PEOPLE_MANAGER',
    department: 'Information Technology & Engineering',
    position: 'Head of Engineering & Ops',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-emp-004',
    employeeId: 'emp-emp-004',
    email: 'budi.pratama@eperformiq.co.id',
    name: 'Budi Pratama',
    role: 'EMPLOYEE',
    department: 'Information Technology & Engineering',
    position: 'Senior Software Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-aud-005',
    employeeId: 'emp-aud-005',
    email: 'bambang.audit@eperformiq.co.id',
    name: 'Bambang Soeprapto, Ak., CA',
    role: 'AUDITOR',
    department: 'Satuan Pengawas Internal (SPI)',
    position: 'Chief Internal Auditor',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

// 2. Strategic Pillars (Balanced Scorecard Perspectives)
export const DUMMY_STRATEGIC_PILLARS: StrategicPillar[] = [
  {
    id: 'pil-01',
    perspective: 'FINANCIAL',
    pillarName: 'Pertumbuhan Pendapatan Berkelanjutan & Efisiensi Anggaran',
    description: 'Optimalisasi realisasi anggaran formasi MPP, EBITDA margin korporasi, dan efisiensi belanja operasional.',
    strategicWeight: 25,
    achievedScore: 92.4,
    targetScore: 100,
  },
  {
    id: 'pil-02',
    perspective: 'CUSTOMER',
    pillarName: 'Kepuasan Stakeholder & Keunggulan Layanan Ekosistem',
    description: 'Indeks kepuasan pengguna internal (CSAT >= 85%) dan pemenuhan SLA rekrutmen tepat waktu.',
    strategicWeight: 25,
    achievedScore: 87.1,
    targetScore: 100,
  },
  {
    id: 'pil-03',
    perspective: 'INTERNAL_PROCESS',
    pillarName: 'Keunggulan Operasional & Zero Fatal SOP Compliance',
    description: 'Kepatuhan tata kelola proses bisnis ISO 9001/30414, 0 fatal audit finding, dan keandalan sistem 99.9%.',
    strategicWeight: 25,
    achievedScore: 94.8,
    targetScore: 100,
  },
  {
    id: 'pil-04',
    perspective: 'LEARNING_GROWTH',
    pillarName: 'Kapabilitas Human Capital & Penguatan Budaya AKHLAK',
    description: 'Rata-rata 24 jam pelatihan/karyawan/tahun, retensi Top 20% Talent, dan indeks kepemimpinan 360.',
    strategicWeight: 25,
    achievedScore: 83.3,
    targetScore: 100,
  },
];

// 3. Employees in the Department (Direct Reports under Danu)
export const DUMMY_EMPLOYEES: Employee[] = [
  {
    id: 'emp-emp-004',
    employeeCode: 'EMP-2022-0042',
    fullName: 'Budi Pratama',
    email: 'budi.pratama@eperformiq.co.id',
    phone: '+62 812-8899-1024',
    department: 'Information Technology & Engineering',
    position: 'Senior Software Engineer',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'PERMANENT',
    baseSalary: 28500000,
    joinDate: '2022-03-15',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    gpa: 3.67,
    rating: 'A',
    nineBoxQuadrant: 'FUTURE_LEADER',
  },
  {
    id: 'emp-005',
    employeeCode: 'EMP-2023-0108',
    fullName: 'Anisa Wijaya, S.Ds.',
    email: 'anisa.wijaya@eperformiq.co.id',
    phone: '+62 813-7766-3321',
    department: 'Information Technology & Engineering',
    position: 'Product Designer (UI/UX)',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'PERMANENT',
    baseSalary: 18000000,
    joinDate: '2023-01-10',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    gpa: 3.52,
    rating: 'B',
    nineBoxQuadrant: 'GROWTH_STAR',
  },
  {
    id: 'emp-006',
    employeeCode: 'EMP-2021-0089',
    fullName: 'Dimas Prasetyo, S.Kom.',
    email: 'dimas.prasetyo@eperformiq.co.id',
    phone: '+62 811-9922-4411',
    department: 'Information Technology & Engineering',
    position: 'DevOps & Site Reliability Engineer',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'PERMANENT',
    baseSalary: 24000000,
    joinDate: '2021-06-01',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    gpa: 3.41,
    rating: 'B',
    nineBoxQuadrant: 'CORE_PLAYER',
  },
  {
    id: 'emp-007',
    employeeCode: 'EMP-2024-0230',
    fullName: 'Rian Hidayat, S.Kom.',
    email: 'rian.hidayat@eperformiq.co.id',
    phone: '+62 815-4433-2211',
    department: 'Information Technology & Engineering',
    position: 'Junior Backend Developer',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'CONTRACT',
    baseSalary: 12500000,
    joinDate: '2024-02-15',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    gpa: 2.85,
    rating: 'C',
    nineBoxQuadrant: 'DILEMMA',
  },
  {
    id: 'emp-008',
    employeeCode: 'EMP-2020-0019',
    fullName: 'Maya Kartika, S.T.',
    email: 'maya.kartika@eperformiq.co.id',
    phone: '+62 818-1122-3344',
    department: 'Information Technology & Engineering',
    position: 'QA Engineering Lead',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'PERMANENT',
    baseSalary: 26000000,
    joinDate: '2020-08-20',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    gpa: 3.78,
    rating: 'A',
    nineBoxQuadrant: 'HIGH_IMPACT',
  },
  {
    id: 'emp-009',
    employeeCode: 'EMP-2026-0312',
    fullName: 'Fajar Nugroho (Probation)',
    email: 'fajar.nugroho@eperformiq.co.id',
    phone: '+62 819-2233-4455',
    department: 'Information Technology & Engineering',
    position: 'Frontend React Specialist',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'PROBATION',
    baseSalary: 16000000,
    joinDate: '2026-07-01',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    gpa: 3.25,
    rating: 'B',
    nineBoxQuadrant: 'CORE_PLAYER',
  },
  {
    id: 'emp-010',
    employeeCode: 'EMP-2018-0005',
    fullName: 'Rizky Pratama (Offboarding)',
    email: 'rizky.offboard@eperformiq.co.id',
    phone: '+62 812-4455-6677',
    department: 'Information Technology & Engineering',
    position: 'Lead Solution Architect',
    managerId: 'emp-mgr-003',
    managerName: 'Raden Mas Danu, S.T., M.Kom.',
    status: 'RESIGNED',
    baseSalary: 35000000,
    joinDate: '2018-04-10',
    lastWorkingDay: '2026-09-30',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    gpa: 3.88,
    rating: 'A',
    nineBoxQuadrant: 'FUTURE_LEADER',
  },
];

// 4. Individual Cascaded KPIs for Budi Pratama
export const DUMMY_BUDI_KPIS: IndividualKPI[] = [
  {
    id: 'kpi-001',
    employeeId: 'emp-emp-004',
    periodId: '2026-Q3',
    strategicPillarId: 'pil-03',
    strategicPillarName: 'Keunggulan Operasional & Zero Fatal SOP Compliance',
    kpiTitle: 'Pencapaian SLA Waktu Tanggap & Resolusi Bug Produksi Tier-1',
    targetValue: 98.0,
    actualValue: 99.2,
    unit: '% On-Time SLA',
    weight: 30,
    achievementPercentage: 101.2,
    status: 'APPROVED',
  },
  {
    id: 'kpi-002',
    employeeId: 'emp-emp-004',
    periodId: '2026-Q3',
    strategicPillarId: 'pil-01',
    strategicPillarName: 'Pertumbuhan Pendapatan Berkelanjutan & Efisiensi Anggaran',
    kpiTitle: 'Optimasi Efisiensi Arsitektur Cloud & Penurunan Server Latency',
    targetValue: 200,
    actualValue: 185,
    unit: 'ms Latency (Lower is better)',
    weight: 25,
    achievementPercentage: 107.5,
    status: 'APPROVED',
  },
  {
    id: 'kpi-003',
    employeeId: 'emp-emp-004',
    periodId: '2026-Q3',
    strategicPillarId: 'pil-03',
    strategicPillarName: 'Keunggulan Operasional & Zero Fatal SOP Compliance',
    kpiTitle: 'Cakupan Unit Testing & Kepatuhan SonarQube Quality Gate',
    targetValue: 85.0,
    actualValue: 88.5,
    unit: '% Code Coverage',
    weight: 25,
    achievementPercentage: 104.1,
    status: 'APPROVED',
  },
  {
    id: 'kpi-004',
    employeeId: 'emp-emp-004',
    periodId: '2026-Q3',
    strategicPillarId: 'pil-04',
    strategicPillarName: 'Kapabilitas Human Capital & Penguatan Budaya AKHLAK',
    kpiTitle: 'Mentoring Junior Developer & Pelaksanaan Tech Talk Bulanan',
    targetValue: 6,
    actualValue: 5,
    unit: 'Sesi Tech Talk & Pairing',
    weight: 20,
    achievementPercentage: 83.3,
    status: 'APPROVED',
  },
];

// 5. Performance Appraisal for Budi Pratama (Detailed Component Breakdown)
export const DUMMY_APPRAISAL_BUDI: PerformanceAppraisal = {
  id: 'app-7b2d1f99',
  periodId: '2026-Q3',
  employeeId: 'emp-emp-004',
  employeeName: 'Budi Pratama',
  employeeCode: 'EMP-2022-0042',
  department: 'Information Technology & Engineering',
  position: 'Senior Software Engineer',
  kpiScore: 92.5,        // 50% = 46.25
  sopScore: 96.0,        // 20% = 19.20
  competencyScore: 85.0, // 15% = 12.75
  coreValuesScore: 90.0, // 15% = 13.50
  totalPercentage: 91.70,
  compositeGPA: 3.67,
  rating: 'A',
  potentialScore: 4.2,
  nineBoxQuadrant: 'FUTURE_LEADER',
  isCalibrated: true,
  calibratedBy: 'Siti Nurhaliza, S.Psi., M.M.',
  calibratedAt: '2026-09-18T10:00:00Z',
};

// 6. SOP & SLA Compliance Logs
export const DUMMY_SOP_LOGS: SOPComplianceRecord[] = [
  {
    id: 'sop-01',
    employeeId: 'emp-emp-004',
    employeeName: 'Budi Pratama',
    periodId: '2026-Q3',
    totalTasks: 142,
    slaBreachCount: 1,
    procedureErrors: 0,
    compliancePercentage: 99.3,
    internalAuditFindings: 'Zero Non-Conformance (Audited ISO 27001)',
  },
  {
    id: 'sop-02',
    employeeId: 'emp-007',
    employeeName: 'Rian Hidayat',
    periodId: '2026-Q3',
    totalTasks: 88,
    slaBreachCount: 8,
    procedureErrors: 3,
    compliancePercentage: 87.5,
    internalAuditFindings: '3 Minor findings: git commit message standard violation',
  },
];

// 7. 360 Peer Reviews for Budi Pratama
export const DUMMY_PEER_REVIEWS: PeerReview360[] = [
  {
    id: 'rev-01',
    evaluateeId: 'emp-emp-004',
    evaluatorId: 'emp-mgr-003',
    evaluatorName: 'Raden Mas Danu, S.T., M.Kom.',
    evaluatorRole: 'Head of Engineering',
    relationshipType: 'SUPERVISOR',
    integrityScore: 4.8,
    collaborationScore: 4.6,
    innovationScore: 4.7,
    averageScore: 4.7,
    feedbackNotes: 'Budi memiliki dedikasi teknis yang luar biasa. Sangat proaktif dalam menyelesaikan incident kritis dan selalu menjaga integritas kode.',
    submittedAt: '2026-09-15T08:30:00Z',
  },
  {
    id: 'rev-02',
    evaluateeId: 'emp-emp-004',
    evaluatorId: 'emp-005',
    evaluatorName: 'Anisa Wijaya',
    evaluatorRole: 'Product Designer',
    relationshipType: 'PEER',
    integrityScore: 4.5,
    collaborationScore: 4.9,
    innovationScore: 4.4,
    averageScore: 4.6,
    feedbackNotes: 'Sangat kooperatif saat sinkronisasi desain Figma ke implementasi Next.js. Sangat menghargai detail interaksi UX.',
    submittedAt: '2026-09-16T14:15:00Z',
  },
  {
    id: 'rev-03',
    evaluateeId: 'emp-emp-004',
    evaluatorId: 'emp-007',
    evaluatorName: 'Rian Hidayat',
    evaluatorRole: 'Junior Backend Developer',
    relationshipType: 'SUBORDINATE',
    integrityScore: 4.7,
    collaborationScore: 4.8,
    innovationScore: 4.5,
    averageScore: 4.67,
    feedbackNotes: 'Mas Budi sangat sabar memberikan panduan code review dan selalu mengajarkan best practice architectural pattern.',
    submittedAt: '2026-09-17T11:20:00Z',
  },
];

// 8. Manpower Planning (MPP Tracker)
export const DUMMY_MANPOWER_PLANS: ManpowerPlan[] = [
  {
    id: 'mpp-01',
    department: 'Information Technology & Engineering',
    position: 'Cloud Infrastructure & DevOps',
    fiscalYear: 2026,
    approvedQuota: 10,
    hiredCount: 8,
    allocatedBudget: 1200000000,
    utilizedBudget: 960000000,
  },
  {
    id: 'mpp-02',
    department: 'Product & UX Design',
    position: 'Lead UX Researcher & Interaction Designer',
    fiscalYear: 2026,
    approvedQuota: 5,
    hiredCount: 5,
    allocatedBudget: 650000000,
    utilizedBudget: 640000000,
  },
  {
    id: 'mpp-03',
    department: 'Finance & Risk Governance',
    position: 'Internal Risk & GCG Analyst',
    fiscalYear: 2026,
    approvedQuota: 4,
    hiredCount: 3,
    allocatedBudget: 480000000,
    utilizedBudget: 350000000,
  },
  {
    id: 'mpp-04',
    department: 'Human Capital Operations',
    position: 'People Partner & Talent Acquisition Specialist',
    fiscalYear: 2026,
    approvedQuota: 6,
    hiredCount: 6,
    allocatedBudget: 550000000,
    utilizedBudget: 530000000,
  },
];

// 9. Recruitment Candidates & QoH Pipeline (Pre-Employment)
export const DUMMY_RECRUITMENT: RecruitmentAssessment[] = [
  {
    id: 'rec-01',
    candidateName: 'Aditya Pratama, S.Kom.',
    appliedPosition: 'Fullstack Next.js Developer',
    department: 'Information Technology & Engineering',
    psychometricScore: 88.0,
    technicalTestScore: 92.5,
    competencyInterviewScore: 86.0,
    computedQoH: 88.8,
    timeToFillDays: 22,
    recruitmentCost: 6500000,
    hiringStatus: 'HIRED',
  },
  {
    id: 'rec-02',
    candidateName: 'Salsabila Putri, S.Si.',
    appliedPosition: 'Data & Analytics Engineer',
    department: 'Information Technology & Engineering',
    psychometricScore: 90.0,
    technicalTestScore: 94.0,
    competencyInterviewScore: 89.0,
    computedQoH: 91.0,
    timeToFillDays: 28,
    recruitmentCost: 8200000,
    hiringStatus: 'OFFERED',
  },
  {
    id: 'rec-03',
    candidateName: 'Gilang Ramadhan',
    appliedPosition: 'Cybersecurity Analyst',
    department: 'Satuan Pengawas Internal (SPI)',
    psychometricScore: 78.0,
    technicalTestScore: 82.0,
    competencyInterviewScore: 80.0,
    computedQoH: 80.0,
    timeToFillDays: 35,
    recruitmentCost: 7000000,
    hiringStatus: 'INTERVIEWED',
  },
  {
    id: 'rec-04',
    candidateName: 'Nurul Hidayati',
    appliedPosition: 'People Experience Officer',
    department: 'Human Capital Operations',
    psychometricScore: 86.0,
    technicalTestScore: 85.0,
    competencyInterviewScore: 91.0,
    computedQoH: 87.3,
    timeToFillDays: 18,
    recruitmentCost: 4500000,
    hiringStatus: 'HIRED',
  },
];

// 10. 30-60-90 Days Onboarding Milestones
export const DUMMY_ONBOARDING: OnboardingMilestone[] = [
  {
    id: 'onb-01',
    employeeId: 'emp-009',
    employeeName: 'Fajar Nugroho',
    position: 'Frontend React Specialist',
    day30Score: 88.0,
    day60Score: 86.5,
    day90Score: 89.0,
    probationPassed: true,
    managerNotes: 'Adaptasi budaya sangat cepat. Pemahaman arsitektur komponen sangat matang. Direkomendasikan konversi ke Karyawan Tetap (PKWTT).',
    conversionDate: '2026-10-01',
  },
  {
    id: 'onb-02',
    employeeId: 'emp-rec-02',
    employeeName: 'Danang Triyanto',
    position: 'Junior QA Engineer',
    day30Score: 75.0,
    day60Score: 78.0,
    day90Score: 80.0,
    probationPassed: false,
    managerNotes: 'Masih membutuhkan perpanjangan supervisi pada test automation framework.',
  },
];

// 11. Offboarding & PP 35/2021 Severance Handover Records
export const DUMMY_OFFBOARDING: OffboardingRequest[] = [
  {
    id: 'off-01',
    employeeId: 'emp-010',
    employeeName: 'Rizky Pratama',
    position: 'Lead Solution Architect',
    department: 'Information Technology & Engineering',
    joinDate: '2018-04-10',
    resignationNoticeDate: '2026-08-30',
    lastWorkingDay: '2026-09-30',
    serviceYears: 8,
    baseSalary: 35000000,
    reasonForLeaving: 'Melanjutkan Studi Doktoral (S3) Luar Negeri',
    isRegrettableAttrition: true, // Top 20% high impact talent
    status: 'CLEARANCE_IN_PROGRESS',
    handoverProgress: 75,
  },
];

export const DUMMY_KNOWLEDGE_HANDOVERS: KnowledgeHandover[] = [
  {
    id: 'hnd-01',
    offboardingRequestId: 'off-01',
    itemName: 'Arsitektur & Kredensial AWS Cloud Production (KMS & Root Access)',
    category: 'ACCESS_KEY',
    handoverToEmployeeName: 'Budi Pratama',
    isVerified: true,
    verifiedBy: 'Raden Mas Danu, S.T., M.Kom.',
    verifiedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'hnd-02',
    offboardingRequestId: 'off-01',
    itemName: 'Dokumentasi Blueprint Sistem Enterprise E-PerformIQ v1.0',
    category: 'DOCUMENTATION',
    handoverToEmployeeName: 'Budi Pratama',
    isVerified: true,
    verifiedBy: 'Raden Mas Danu, S.T., M.Kom.',
    verifiedAt: '2026-09-19T09:30:00Z',
  },
  {
    id: 'hnd-03',
    offboardingRequestId: 'off-01',
    itemName: 'Pengembalian Laptop MacBook Pro M3 Max & ID Card Akses Gedung',
    category: 'PHYSICAL_ASSET',
    handoverToEmployeeName: 'General Affairs / IT Asset Officer',
    isVerified: false,
  },
];

export const DUMMY_SEVERANCE: SeveranceCalculation = {
  id: 'sev-01',
  offboardingRequestId: 'off-01',
  employeeName: 'Rizky Pratama',
  serviceYears: 8,
  baseSalary: 35000000,
  severancePay: 0, // Resign sukarela
  serviceAppreciationPay: 0,
  compensationPay: 5250000, // UPH sisa cuti 12 hari
  dplkTopup: 168000000,     // DPLK akumulasi 8 tahun
  totalDisbursement: 173250000,
  slaDisbursedDays: 3,
  isPaid: true,
  paymentReferenceNo: 'TRX-DISB-202609-0098',
  paidAt: '2026-09-19T14:00:00Z',
};

// 12. Lifetime Contribution Index (LCI) & Legacy Vault
export const DUMMY_LCI: LifetimeContribution[] = [
  {
    id: 'lci-01',
    employeeId: 'emp-emp-004',
    employeeName: 'Budi Pratama',
    achievementTitle: 'Paten Sistem Kompresi Data Log Kinerja Karyawan Berbasis Delta Z-Score',
    achievementType: 'PATENT',
    quantifiedImpactIdr: 450000000,
    pointsAwarded: 150,
    dateAchieved: '2025-11-12',
  },
  {
    id: 'lci-02',
    employeeId: 'emp-emp-004',
    employeeName: 'Budi Pratama',
    achievementTitle: 'Kaizen Inovasi: Otomatisasi Pipeline CI/CD Mengurangi Biaya Cloud 30%',
    achievementType: 'KAIZEN_SAVING',
    quantifiedImpactIdr: 280000000,
    pointsAwarded: 100,
    dateAchieved: '2026-04-18',
  },
  {
    id: 'lci-03',
    employeeId: 'emp-010',
    employeeName: 'Rizky Pratama',
    achievementTitle: 'Arsitektur Enterprise Core Service Berkecepatan 30.000 req/detik',
    achievementType: 'REVENUE_IMPACT',
    quantifiedImpactIdr: 1200000000,
    pointsAwarded: 300,
    dateAchieved: '2024-07-25',
  },
];

// 13. Immutable GCG Audit Logs
export const DUMMY_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-20T08:15:22Z',
    userName: 'Siti Nurhaliza, S.Psi., M.M.',
    userRole: 'HR_MANAGER',
    actionType: 'CALIBRATE',
    entityName: 'performance_appraisals',
    recordId: 'app-7b2d1f99',
    description: 'Komite Kalibrasi mengesahkan skor akhir Budi Pratama (GPA 3.67, Rating A). Status terkunci sesuai GCG.',
    oldData: { status: 'DRAFT', compositeGPA: 3.65 },
    newData: { status: 'LOCKED', compositeGPA: 3.67, isCalibrated: true },
    ipAddress: '10.24.110.12',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-19T14:02:11Z',
    userName: 'Siti Nurhaliza, S.Psi., M.M.',
    userRole: 'HR_MANAGER',
    actionType: 'DISBURSE',
    entityName: 'severance_calculations',
    recordId: 'sev-01',
    description: 'Pencairan hak kompensasi & DPLK Rizky Pratama sejumlah Rp 173.250.000 via Bank H2H disetujui.',
    oldData: { isPaid: false },
    newData: { isPaid: true, paymentReferenceNo: 'TRX-DISB-202609-0098' },
    ipAddress: '10.24.110.12',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-18T10:45:00Z',
    userName: 'Raden Mas Danu, S.T., M.Kom.',
    userRole: 'PEOPLE_MANAGER',
    actionType: 'APPROVE',
    entityName: 'individual_kpis',
    recordId: 'kpi-001',
    description: 'Approval sasaran kerja kuartalan KPI Budi Pratama terkait SLA Bug Resolusi Tier-1.',
    oldData: { status: 'SUBMITTED' },
    newData: { status: 'APPROVED' },
    ipAddress: '10.24.110.45',
  },
  {
    id: 'aud-004',
    timestamp: '2026-09-17T09:12:30Z',
    userName: 'Ir. Hendra Gunawan, M.B.A.',
    userRole: 'BOD',
    actionType: 'UPDATE',
    entityName: 'strategic_pillars',
    recordId: 'pil-01',
    description: 'Pembaruan bobot prioritas RJPP Korporasi pada Pilar Finansial disahkan menjadi 25%.',
    oldData: { strategicWeight: 20 },
    newData: { strategicWeight: 25 },
    ipAddress: '10.24.100.5',
  },
];
