/**
 * Seed referensi pendidikan (WS-13) — jurusan umum + contoh institusi.
 * Data ini sebagai FALLBACK lokal; pencarian dapat diperkaya dari API publik
 * (api-sekolah-indonesia untuk sekolah; PDDIKTI/Sivitas untuk kampus).
 */

export const SEED_MAJORS: Array<{ name: string; groupName: string }> = [
  { name: 'Teknik Informatika', groupName: 'Teknologi Informasi' },
  { name: 'Sistem Informasi', groupName: 'Teknologi Informasi' },
  { name: 'Ilmu Komputer', groupName: 'Teknologi Informasi' },
  { name: 'Teknik Komputer', groupName: 'Teknologi Informasi' },
  { name: 'Teknologi Informasi', groupName: 'Teknologi Informasi' },
  { name: 'Rekayasa Perangkat Lunak', groupName: 'Teknologi Informasi' },
  { name: 'Data Science', groupName: 'Teknologi Informasi' },
  { name: 'Sistem Informasi Akuntansi', groupName: 'Teknologi Informasi' },
  { name: 'Teknik Elektro', groupName: 'Teknik' },
  { name: 'Teknik Industri', groupName: 'Teknik' },
  { name: 'Teknik Mesin', groupName: 'Teknik' },
  { name: 'Teknik Sipil', groupName: 'Teknik' },
  { name: 'Teknik Kimia', groupName: 'Teknik' },
  { name: 'Arsitektur', groupName: 'Teknik' },
  { name: 'Manajemen', groupName: 'Ekonomi & Bisnis' },
  { name: 'Akuntansi', groupName: 'Ekonomi & Bisnis' },
  { name: 'Ekonomi', groupName: 'Ekonomi & Bisnis' },
  { name: 'Ekonomi Pembangunan', groupName: 'Ekonomi & Bisnis' },
  { name: 'Bisnis Digital', groupName: 'Ekonomi & Bisnis' },
  { name: 'Perbankan', groupName: 'Ekonomi & Bisnis' },
  { name: 'Psikologi', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Hukum', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Komunikasi', groupName: 'Sosial & Humaniora' },
  { name: 'Hubungan Internasional', groupName: 'Sosial & Humaniora' },
  { name: 'Administrasi Publik', groupName: 'Sosial & Humaniora' },
  { name: 'Administrasi Bisnis', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Politik', groupName: 'Sosial & Humaniora' },
  { name: 'Sosiologi', groupName: 'Sosial & Humaniora' },
  { name: 'Kesehatan Masyarakat', groupName: 'Kesehatan' },
  { name: 'Kedokteran', groupName: 'Kesehatan' },
  { name: 'Farmasi', groupName: 'Kesehatan' },
  { name: 'Keperawatan', groupName: 'Kesehatan' },
  { name: 'Gizi', groupName: 'Kesehatan' },
  { name: 'Pendidikan Bahasa Inggris', groupName: 'Pendidikan' },
  { name: 'Pendidikan Matematika', groupName: 'Pendidikan' },
  { name: 'Pendidikan Guru Sekolah Dasar', groupName: 'Pendidikan' },
  { name: 'Desain Komunikasi Visual', groupName: 'Seni & Desain' },
  { name: 'Desain Produk', groupName: 'Seni & Desain' },
  { name: 'Seni Rupa', groupName: 'Seni & Desain' },
  { name: 'Matematika', groupName: 'Sains' },
  { name: 'Statistika', groupName: 'Sains' },
  { name: 'Fisika', groupName: 'Sains' },
  { name: 'Biologi', groupName: 'Sains' },
  { name: 'Kimia', groupName: 'Sains' },
  { name: 'Agribisnis', groupName: 'Pertanian' },
  { name: 'Teknologi Pangan', groupName: 'Pertanian' },
];

export const SEED_INSTITUTIONS: Array<{ name: string; level: string; code?: string; city?: string; province?: string }> = [
  // --- Perguruan Tinggi Negeri (PTN) utama (kode PDDIKTI bila diketahui) ---
  { name: 'Universitas Indonesia', level: 'PT', code: '001001', city: 'Depok', province: 'Jawa Barat' },
  { name: 'Institut Teknologi Bandung', level: 'PT', code: '002001', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Gadjah Mada', level: 'PT', code: '003001', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Institut Teknologi Sepuluh Nopember', level: 'PT', code: '002002', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Airlangga', level: 'PT', code: '001012', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Diponegoro', level: 'PT', code: '002004', city: 'Semarang', province: 'Jawa Tengah' },
  { name: 'Universitas Brawijaya', level: 'PT', code: '001013', city: 'Malang', province: 'Jawa Timur' },
  { name: 'Universitas Padjadjaran', level: 'PT', code: '001011', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Sebelas Maret', level: 'PT', code: '001014', city: 'Surakarta', province: 'Jawa Tengah' },
  { name: 'Universitas Negeri Yogyakarta', level: 'PT', code: '001038', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Negeri Malang', level: 'PT', code: '001050', city: 'Malang', province: 'Jawa Timur' },
  { name: 'Universitas Negeri Surabaya', level: 'PT', code: '001026', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Negeri Semarang', level: 'PT', code: '001048', city: 'Semarang', province: 'Jawa Tengah' },
  { name: 'Universitas Negeri Padang', level: 'PT', code: '001015', city: 'Padang', province: 'Sumatera Barat' },
  { name: 'Universitas Sumatera Utara', level: 'PT', code: '001002', city: 'Medan', province: 'Sumatera Utara' },
  { name: 'Universitas Andalas', level: 'PT', code: '001003', city: 'Padang', province: 'Sumatera Barat' },
  { name: 'Universitas Riau', level: 'PT', code: '001004', city: 'Pekanbaru', province: 'Riau' },
  { name: 'Universitas Sriwijaya', level: 'PT', code: '001005', city: 'Palembang', province: 'Sumatera Selatan' },
  { name: 'Universitas Lampung', level: 'PT', code: '001006', city: 'Bandar Lampung', province: 'Lampung' },
  { name: 'Universitas Syiah Kuala', level: 'PT', code: '001007', city: 'Banda Aceh', province: 'Aceh' },
  { name: 'Universitas Udayana', level: 'PT', code: '001008', city: 'Denpasar', province: 'Bali' },
  { name: 'Universitas Mataram', level: 'PT', code: '001009', city: 'Mataram', province: 'Nusa Tenggara Barat' },
  { name: 'Universitas Nusa Cendana', level: 'PT', code: '001010', city: 'Kupang', province: 'Nusa Tenggara Timur' },
  { name: 'Universitas Hasanuddin', level: 'PT', code: '001018', city: 'Makassar', province: 'Sulawesi Selatan' },
  { name: 'Universitas Sam Ratulangi', level: 'PT', code: '001019', city: 'Manado', province: 'Sulawesi Utara' },
  { name: 'Universitas Halu Oleo', level: 'PT', code: '001020', city: 'Kendari', province: 'Sulawesi Tenggara' },
  { name: 'Universitas Tadulako', level: 'PT', code: '001021', city: 'Palu', province: 'Sulawesi Tengah' },
  { name: 'Universitas Pattimura', level: 'PT', code: '001022', city: 'Ambon', province: 'Maluku' },
  { name: 'Universitas Cenderawasih', level: 'PT', code: '001023', city: 'Jayapura', province: 'Papua' },
  { name: 'Universitas Tanjungpura', level: 'PT', code: '001016', city: 'Pontianak', province: 'Kalimantan Barat' },
  { name: 'Universitas Lambung Mangkurat', level: 'PT', code: '001017', city: 'Banjarmasin', province: 'Kalimantan Selatan' },
  { name: 'Universitas Mulawarman', level: 'PT', code: '001024', city: 'Samarinda', province: 'Kalimantan Timur' },
  { name: 'Universitas Palangka Raya', level: 'PT', code: '001025', city: 'Palangka Raya', province: 'Kalimantan Tengah' },
  { name: 'Universitas Jenderal Soedirman', level: 'PT', code: '002023', city: 'Purwokerto', province: 'Jawa Tengah' },
  { name: 'Universitas Jember', level: 'PT', code: '001027', city: 'Jember', province: 'Jawa Timur' },
  { name: 'Universitas Bengkulu', level: 'PT', code: '001028', city: 'Bengkulu', province: 'Bengkulu' },
  { name: 'Universitas Jambi', level: 'PT', code: '001029', city: 'Jambi', province: 'Jambi' },
  { name: 'Universitas Sultan Ageng Tirtayasa', level: 'PT', code: '001039', city: 'Serang', province: 'Banten' },
  { name: 'Universitas Negeri Gorontalo', level: 'PT', code: '001040', city: 'Gorontalo', province: 'Gorontalo' },
  { name: 'Universitas Negeri Manado', level: 'PT', code: '001041', city: 'Tondano', province: 'Sulawesi Utara' },
  { name: 'Universitas Negeri Makassar', level: 'PT', code: '001042', city: 'Makassar', province: 'Sulawesi Selatan' },
  { name: 'Universitas Negeri Jakarta', level: 'PT', code: '001044', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Pendidikan Indonesia', level: 'PT', code: '001046', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Negeri Medan', level: 'PT', code: '001047', city: 'Medan', province: 'Sumatera Utara' },
  { name: 'UIN Syarif Hidayatullah Jakarta', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'UIN Sunan Kalijaga Yogyakarta', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Institut Pertanian Bogor', level: 'PT', code: '002003', city: 'Bogor', province: 'Jawa Barat' },
  { name: 'Universitas Pertahanan', level: 'PT', city: 'Bogor', province: 'Jawa Barat' },
  { name: 'Politeknik Negeri Jakarta', level: 'PT', city: 'Depok', province: 'Jawa Barat' },
  { name: 'Politeknik Negeri Bandung', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Politeknik Elektronika Negeri Surabaya', level: 'PT', city: 'Surabaya', province: 'Jawa Timur' },
  // --- Perguruan Tinggi Swasta (PTS) terkemuka ---
  { name: 'Universitas Bina Nusantara', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Telkom', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Multimedia Nusantara', level: 'PT', city: 'Tangerang', province: 'Banten' },
  { name: 'Universitas Pelita Harapan', level: 'PT', city: 'Tangerang', province: 'Banten' },
  { name: 'Universitas Katolik Indonesia Atma Jaya', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Trisakti', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Mercu Buana', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Gunadarma', level: 'PT', city: 'Depok', province: 'Jawa Barat' },
  { name: 'Universitas Islam Indonesia', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Muhammadiyah Yogyakarta', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Ahmad Dahlan', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Katolik Parahyangan', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Kristen Petra', level: 'PT', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Ciputra', level: 'PT', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Dian Nuswantoro', level: 'PT', city: 'Semarang', province: 'Jawa Tengah' },
  { name: 'Universitas Bunda Mulia', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Bakrie', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Prasetiya Mulya', level: 'PT', city: 'Tangerang', province: 'Banten' },
  { name: 'Universitas Atma Jaya Yogyakarta', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Sanata Dharma', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Universitas Tarumanagara', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Kristen Satya Wacana', level: 'PT', city: 'Salatiga', province: 'Jawa Tengah' },
  { name: 'Universitas Islam Negeri Maulana Malik Ibrahim', level: 'PT', city: 'Malang', province: 'Jawa Timur' },
  // --- Contoh sekolah menengah ---
  { name: 'SMAN 1 Jakarta', level: 'SMA/SMK', city: 'Jakarta Pusat', province: 'DKI Jakarta' },
  { name: 'SMAN 8 Jakarta', level: 'SMA/SMK', city: 'Jakarta Selatan', province: 'DKI Jakarta' },
  { name: 'SMAN 3 Bandung', level: 'SMA/SMK', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'SMAN 1 Yogyakarta', level: 'SMA/SMK', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'SMKN 1 Jakarta', level: 'SMA/SMK', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'SMKN 2 Surabaya', level: 'SMA/SMK', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'SMAN 5 Surabaya', level: 'SMA/SMK', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'SMAN 1 Medan', level: 'SMA/SMK', city: 'Medan', province: 'Sumatera Utara' },
];
