/**
 * Seed referensi pendidikan (WS-13) — jurusan umum + contoh institusi.
 * Data ini sebagai FALLBACK lokal; pencarian dapat diperkaya dari API publik
 * (api-sekolah-indonesia untuk sekolah; PDDIKTI/Sivitas untuk kampus).
 */

export const SEED_MAJORS: Array<{ name: string; groupName: string }> = [
  { name: 'Teknik Informatika', groupName: 'Teknologi Informasi' },
  { name: 'Sistem Informasi', groupName: 'Teknologi Informasi' },
  { name: 'Ilmu Komputer', groupName: 'Teknologi Informasi' },
  { name: 'Teknik Komputer', groupName: 'Teknologi Informasi' },
  { name: 'Teknologi Informasi', groupName: 'Teknologi Informasi' },
  { name: 'Rekayasa Perangkat Lunak', groupName: 'Teknologi Informasi' },
  { name: 'Data Science', groupName: 'Teknologi Informasi' },
  { name: 'Sistem Informasi Akuntansi', groupName: 'Teknologi Informasi' },
  { name: 'Teknik Elektro', groupName: 'Teknik' },
  { name: 'Teknik Industri', groupName: 'Teknik' },
  { name: 'Teknik Mesin', groupName: 'Teknik' },
  { name: 'Teknik Sipil', groupName: 'Teknik' },
  { name: 'Teknik Kimia', groupName: 'Teknik' },
  { name: 'Arsitektur', groupName: 'Teknik' },
  { name: 'Manajemen', groupName: 'Ekonomi & Bisnis' },
  { name: 'Akuntansi', groupName: 'Ekonomi & Bisnis' },
  { name: 'Ekonomi', groupName: 'Ekonomi & Bisnis' },
  { name: 'Ekonomi Pembangunan', groupName: 'Ekonomi & Bisnis' },
  { name: 'Bisnis Digital', groupName: 'Ekonomi & Bisnis' },
  { name: 'Perbankan', groupName: 'Ekonomi & Bisnis' },
  { name: 'Psikologi', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Hukum', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Komunikasi', groupName: 'Sosial & Humaniora' },
  { name: 'Hubungan Internasional', groupName: 'Sosial & Humaniora' },
  { name: 'Administrasi Publik', groupName: 'Sosial & Humaniora' },
  { name: 'Administrasi Bisnis', groupName: 'Sosial & Humaniora' },
  { name: 'Ilmu Politik', groupName: 'Sosial & Humaniora' },
  { name: 'Sosiologi', groupName: 'Sosial & Humaniora' },
  { name: 'Kesehatan Masyarakat', groupName: 'Kesehatan' },
  { name: 'Kedokteran', groupName: 'Kesehatan' },
  { name: 'Farmasi', groupName: 'Kesehatan' },
  { name: 'Keperawatan', groupName: 'Kesehatan' },
  { name: 'Gizi', groupName: 'Kesehatan' },
  { name: 'Pendidikan Bahasa Inggris', groupName: 'Pendidikan' },
  { name: 'Pendidikan Matematika', groupName: 'Pendidikan' },
  { name: 'Pendidikan Guru Sekolah Dasar', groupName: 'Pendidikan' },
  { name: 'Desain Komunikasi Visual', groupName: 'Seni & Desain' },
  { name: 'Desain Produk', groupName: 'Seni & Desain' },
  { name: 'Seni Rupa', groupName: 'Seni & Desain' },
  { name: 'Matematika', groupName: 'Sains' },
  { name: 'Statistika', groupName: 'Sains' },
  { name: 'Fisika', groupName: 'Sains' },
  { name: 'Biologi', groupName: 'Sains' },
  { name: 'Kimia', groupName: 'Sains' },
  { name: 'Agribisnis', groupName: 'Pertanian' },
  { name: 'Teknologi Pangan', groupName: 'Pertanian' },
];

export const SEED_INSTITUTIONS: Array<{ name: string; level: string; code?: string; city?: string; province?: string }> = [
  { name: 'Universitas Indonesia', level: 'PT', city: 'Depok', province: 'Jawa Barat' },
  { name: 'Institut Teknologi Bandung', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Gadjah Mada', level: 'PT', city: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Institut Teknologi Sepuluh Nopember', level: 'PT', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Airlangga', level: 'PT', city: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Universitas Diponegoro', level: 'PT', city: 'Semarang', province: 'Jawa Tengah' },
  { name: 'Universitas Brawijaya', level: 'PT', city: 'Malang', province: 'Jawa Timur' },
  { name: 'Universitas Padjadjaran', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'Universitas Bina Nusantara', level: 'PT', city: 'Jakarta', province: 'DKI Jakarta' },
  { name: 'Universitas Telkom', level: 'PT', city: 'Bandung', province: 'Jawa Barat' },
  { name: 'SMAN 1 Jakarta', level: 'SMA/SMK', city: 'Jakarta Pusat', province: 'DKI Jakarta' },
  { name: 'SMKN 1 Jakarta', level: 'SMA/SMK', city: 'Jakarta', province: 'DKI Jakarta' },
];
